version: "3"

services:
  db:
    container_name: p2p_db
    image: postgres:12-alpine
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=OperationalError
      - POSTGRES_DB=postgres
    volumes: 
        - ./postgres-data:/var/lib/postgresql/data
        - ./sql/create_db.sql:/docker-entrypoint-initdb.d/create_db.sql
    restart: unless-stopped
  web:
    container_name: p2p_web
    build: .
    # command: "uvicorn main:app --host 0.0.0.0 --port 8080 --reload"
    env_file:
      - .env
    volumes:
      - .:/app/
    restart: unless-stopped
    ports:
      - "8081:8080"
    depends_on:
      - db