version: "3"

services:
  db:
    container_name: p2p_db
    image: postgres:12-alpine
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=OperationalError
      - POSTGRES_DB=postgres
    volumes: 
        - ./postgres-data:/var/lib/postgresql/data
        - ./sql/create_db.sql:/docker-entrypoint-initdb.d/create_db.sql
    restart: unless-stopped
  cache:
    container_name: p2p_cache
    image: redis:6.2.5-alpine
    command: redis-server --requirepass super_scuere
    ports:
      - "6379:6379"
    volumes:
      - ./redis/data:/data
    restart: unless-stopped
  web:
    container_name: p2p_web
    build: .
    env_file:
      - .env
    volumes:
      - .:/app/
    restart: unless-stopped
    ports:
      - "8081:8080"
    depends_on:
      - db
      - cache
    labels:
      kompose.service.type: LoadBalancer