# Generated by Django 3.2.7 on 2021-09-23 19:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('messenger', '0002_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='messagehistory',
            options={'ordering': ('-updated_at',)},
        ),
    ]
